export type MediaType = 'video' | 'youtube' | 'image' | 'text'

export interface Highlight {
  icon: string
  text: string
}

export interface UpdateEntry {
  id: string
  date: string
  type: MediaType
  mediaUrl?: string
  tags?: string[]
  highlights?: Highlight[]
}

// Placeholder — will be generated by scripts/media.py sync after video upload
export const updates: UpdateEntry[] = []
